#!/bin/bash
# Wrapper script to export environment variables

# source configuration with environment variables
. ~/.oh-servers

# Get this script's directory
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Run the real script
$DIR/oh-mysql $1
