#!/usr/bin/perl
use strict;
use warnings;
use Net::SSH qw(ssh_cmd);

my $host = shift;
my $release = shift;

die "Usage: $0 <host> <ubuntu_release>\n" unless $host and $release;

my %steps = (
    a_upgrade => [
        'DEBIAN_FRONTEND=noninteractive apt-get update && apt-get -y upgrade',
    ],
    b_puppet_master => [
        "wget http://apt.puppetlabs.com/puppetlabs-release-$release.deb",
        "DEBIAN_FRONTEND=noninteractive dpkg -i puppetlabs-release-$release.deb",
        'DEBIAN_FRONTEND=noninteractive apt-get -y install puppetmaster',
    ],
    c_puppet_client => [
        "wget http://apt.puppetlabs.com/puppetlabs-release-$release.deb",
        "DEBIAN_FRONTEND=noninteractive dpkg -i puppetlabs-release-$release.deb",
        'DEBIAN_FRONTEND=noninteractive apt-get -y install puppet',
    ],
);

for my $step ( sort keys %steps ) {
    print "==> Running step '$step'\n";
    for my $cmd ( @{ $steps{$step} } ) {
        print "--> Running command '$cmd'\n";
        eval { ssh_cmd( "root\@$host", $cmd ); };
        print "Continuing after error: $@" if $@;
    }
}

exit 0;
